VENV := justfile_directory() + "/.venv"
PYTHON := justfile_directory() + "/.venv/bin/python"
PKG := "."

help:
  @just --list

# Build the package (into `dist/`)
build:
  cd {{PKG}} && \
  pyright . && \
  rm -drf dist && \
  cp ../README.md . && \
  {{PYTHON}} -m build && \
  rm -drf build

# Publish `dist/*` to pypi, then delete
publish: build
  cd {{PKG}} && \
  {{PYTHON}} -m twine upload dist/* && \
  rm -drf dist && rm README.md

# Increase patch version
patch:
  $CIT_SCRIPTS/bump.sh {{PKG}}/pyproject.toml

# Build and publish
republish: patch build publish
